version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
      
artifacts:
  files:
    - '**/*'

reports:
  jest_reports:
    files:
      - Unit Tests
    file-format: JUNITXML
    base-directory: "."
