version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install --save-dev jest-junit
      - npm install -g jest
  build:
    commands:
      - npm build
      - npm test
artifacts:
  files:
    - '**/*'
reports:
  jest_reports:
    files:
      - <report filename>
    file-format: JUNITXML
    base-directory: <test report directory>    

