version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install axios
      - npm install --save-dev jest
  build:
    commands:
      - npm build
      - npm test

artifacts:
  files:
    - '**/*'

reports:
  jest_reports:
    files:
      - My Test Case
    file-format: JUNITXML
    base-directory: "."
